Add helm chart value for image digest
ricoberger/vault-secrets-operator pull request #162
Opened 2022-08-10 22:05 UTC by Zarmbinski

2022-08-12 08:17 UTC, ricoberger requested changes
Hi @Zarmbinski, thanks for your contribution 🙂.

I think you have to add a `:` and `@` in the helpers function.

Can you please also add the `image.digest` property to the `values.yaml` file.

2022-08-12 08:17 UTC, ricoberger commented on charts/vault-secrets-operator/templates/_helpers.tpl
> +    {{ .Values.image.digest }}
```suggestion
    @{{ .Values.image.digest }}
```

2022-08-12 08:17 UTC, ricoberger commented on charts/vault-secrets-operator/templates/_helpers.tpl
> +    {{ .Values.image.tag }}
```suggestion
    :{{ .Values.image.tag }}
```

2022-08-12 16:11 UTC, Zarmbinski commented on charts/vault-secrets-operator/templates/_helpers.tpl
> +    {{ .Values.image.digest }}
Good call. It's been fixed 👍

2022-08-12 16:11 UTC, Zarmbinski commented on charts/vault-secrets-operator/templates/_helpers.tpl
> +    {{ .Values.image.tag }}
Done

2022-08-12 16:11 UTC, Zarmbinski commented
> Hi @Zarmbinski, thanks for your contribution 🙂.
> 
> I think you have to add a `:` and `@` in the helpers function.
> 
> Can you please also add the `image.digest` property to the `values.yaml` file.

Good catch. I've made the requested changes 👍

2022-08-15 17:56 UTC, ricoberger approved these changes

2022-08-15 17:56 UTC, ricoberger commented
Thanks again for your work 🙂

2022-08-15 17:56 UTC, merged

2022-08-15 19:34 UTC, Zarmbinski commented
> Thanks again for your work 🙂

Thank you! It's an honor to contribute to such an excellent tool